"""add is_passed field to solution table

Revision ID: 04181690e0e1
Revises: 9454f8f98cf0
Create Date: 2020-04-20 03:13:35.629542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04181690e0e1'
down_revision = '9454f8f98cf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solution', sa.Column('is_passed', sa.Boolean(), nullable=False, default=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solution', 'is_passed')
    # ### end Alembic commands ###
