"""add name field to task table

Revision ID: 086d0834a6b5
Revises: b9ac368faaa3
Create Date: 2020-05-06 23:17:52.343099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '086d0834a6b5'
down_revision = 'b9ac368faaa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('name', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'name')
    # ### end Alembic commands ###
