"""make user email field unique

Revision ID: 28901be7e869
Revises: efcea48b84ba
Create Date: 2020-05-06 19:01:32.915654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28901be7e869'
down_revision = 'efcea48b84ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
