"""add team and team_member tables

Revision ID: 2bb738f60f10
Revises: 8a91bebea015
Create Date: 2020-05-09 03:14:01.198370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bb738f60f10'
down_revision = '8a91bebea015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
        sa.Column('id', sa.Text(), nullable=False),
        sa.Column('name', sa.Text(), nullable=False),
        sa.Column('contest_id', sa.Text(), nullable=False),
        sa.Column('trainer_id', sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(['contest_id'], ['contest.id'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['trainer_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_member',
        sa.Column('id', sa.Text(), nullable=False),
        sa.Column('user_id', sa.Text(), nullable=False),
        sa.Column('team_id', sa.Text(), nullable=False),
        sa.Column('status', sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(['team_id'], ['team.id'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_member')
    op.drop_table('team')
    # ### end Alembic commands ###
