"""add team_id field to solution

Revision ID: 5d45108b53b3
Revises: ad822d3792eb
Create Date: 2020-05-22 15:18:03.930320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d45108b53b3'
down_revision = 'ad822d3792eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solution', sa.Column('team_id', sa.Text(), nullable=False))
    op.create_foreign_key(None, 'solution', 'team', ['team_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'solution', type_='foreignkey')
    op.drop_column('solution', 'team_id')
    # ### end Alembic commands ###
