"""add max_participants field to contest table

Revision ID: 634791316640
Revises: 086d0834a6b5
Create Date: 2020-05-08 20:08:27.408197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '634791316640'
down_revision = '086d0834a6b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contest', sa.Column('max_participants', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contest', 'max_participants')
    # ### end Alembic commands ###
