"""add creator_id to contest

Revision ID: 8a91bebea015
Revises: f9ca37d996ca
Create Date: 2020-05-09 02:07:04.129474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a91bebea015'
down_revision = 'f9ca37d996ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contest', sa.Column('creator_id', sa.Text(), nullable=False))
    op.create_foreign_key(None, 'contest', 'user', ['creator_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contest', type_='foreignkey')
    op.drop_column('contest', 'creator_id')
    # ### end Alembic commands ###
