"""add created_at field to solution table

Revision ID: 8a9a1c9d2dd1
Revises: 5d45108b53b3
Create Date: 2020-06-13 22:35:37.164553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a9a1c9d2dd1'
down_revision = '5d45108b53b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solution', sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solution', 'created_at')
    # ### end Alembic commands ###
