"""add timezone to contest datetimes fields

Revision ID: 8e5b1400d605
Revises: 98f6859c43bd
Create Date: 2020-05-13 01:03:10.221995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e5b1400d605'
down_revision = '98f6859c43bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contest', 'start_date', type_=sa.TIMESTAMP(timezone=True))
    op.alter_column('contest', 'end_date', type_=sa.TIMESTAMP(timezone=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contest', 'start_date', type_=sa.DATETIME())
    op.alter_column('contest', 'end_date', type_=sa.DATETIME())
    # ### end Alembic commands ###
