"""change img_path column name

Revision ID: a50b0a4fcf6a
Revises: bf49f97aac10
Create Date: 2020-05-05 19:57:42.541005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a50b0a4fcf6a'
down_revision = 'bf49f97aac10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contest', sa.Column('image_path', sa.Text(), nullable=True))
    op.drop_column('contest', 'img_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contest', sa.Column('img_path', sa.TEXT(), nullable=True))
    op.drop_column('contest', 'image_path')
    # ### end Alembic commands ###
