"""add user_id field to solution

Revision ID: ad822d3792eb
Revises: 8e5b1400d605
Create Date: 2020-05-21 20:43:46.059906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad822d3792eb'
down_revision = '8e5b1400d605'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solution', sa.Column('user_id', sa.Text(), nullable=False))
    op.create_foreign_key(None, 'solution', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'solution', type_='foreignkey')
    op.drop_column('solution', 'user_id')
    # ### end Alembic commands ###
