"""add start_date and end_date columns to contest table

Revision ID: b9ac368faaa3
Revises: a6af0b07208b
Create Date: 2020-05-06 16:06:15.149378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9ac368faaa3'
down_revision = 'a6af0b07208b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contest', sa.Column('end_date', sa.DateTime(), nullable=False))
    op.add_column('contest', sa.Column('start_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contest', 'start_date')
    op.drop_column('contest', 'end_date')
    # ### end Alembic commands ###
