"""add img_path field to contest table

Revision ID: bf49f97aac10
Revises: 0f3d43254aed
Create Date: 2020-05-05 16:54:19.229021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf49f97aac10'
down_revision = '0f3d43254aed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contest', sa.Column('img_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contest', 'img_path')
    # ### end Alembic commands ###
