"""add public field to task_io table

Revision ID: e3fe8fb41907
Revises: 8a9a1c9d2dd1
Create Date: 2020-06-14 01:57:44.206156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3fe8fb41907'
down_revision = '8a9a1c9d2dd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_io', sa.Column('public', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_io', 'public')
    # ### end Alembic commands ###
