"""rename user columns, add email, remove salt

Revision ID: efcea48b84ba
Revises: f181221a3099
Create Date: 2020-05-06 16:33:52.398889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efcea48b84ba'
down_revision = 'f181221a3099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.Text(), nullable=False))
    op.add_column('user', sa.Column('first_name', sa.Text(), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.Text(), nullable=False))
    op.drop_column('user', 'salt')
    op.drop_column('user', 'firstname')
    op.drop_column('user', 'lastname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lastname', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('firstname', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('salt', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
