"""add user roles

Revision ID: f181221a3099
Revises: a6af0b07208b
Create Date: 2020-05-06 15:33:45.340382

"""
import uuid

import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import table, column
from sqlalchemy import String


# revision identifiers, used by Alembic.
revision = 'f181221a3099'
down_revision = 'a6af0b07208b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
        sa.Column('id', sa.Text(), nullable=False),
        sa.Column('role', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('role_id', sa.Text(), nullable=False))
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    user_roles_table = table(
        'role',
        column('id', String),
        column('role', String)
    )

    op.bulk_insert(
        user_roles_table,
        [
            {'id': str(uuid.uuid4()), 'role': role}
            for role in ('trainer', 'participant', 'organizer')
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'role_id')
    op.drop_table('role')
    # ### end Alembic commands ###
